### ISSUE TITLE
'trema' does not work

### ISSUE THREAD

**Issue by chibacchie** [trema/trema-edge#26]
```
$ ./trema run src/examples/learning_switch/learning-switch.rb -c src/examples/learning_switch/learning_switch.conf
/home/whoami/.rvm/rubies/ruby-2.0.0-rc2/lib/ruby/site_ruby/2.0.0/rubygems/custom_require.rb:36:in `require': cannot load such file -- gli (LoadError)
        from /home/whoami/.rvm/rubies/ruby-2.0.0-rc2/lib/ruby/site_ruby/2.0.0/rubygems/custom_require.rb:36:in `require'
        from ././bin/trema:25:in `<main>'
$ gem install gli
Fetching: gli-2.5.6.gem (100%)
Successfully installed gli-2.5.6
1 gem installed
Installing ri documentation for gli-2.5.6...
Building YARD (yri) index for gli-2.5.6...
Installing RDoc documentation for gli-2.5.6...
$ ./trema run src/examples/learning_switch/learning-switch.rb -c src/examples/learning_switch/learning_switch.conf
ERROR: Trema is not compiled yet!

Please try the following command:
% ./build.rb
error: exit
```

**Comment by nickkaranatsios** [comment]
Takamiya-san 

The trema run command used to work with the old build could you please confirm. 
Chiba-san if you are in a hurry comment out the executables.rb that calls the path method for tremashark and it should work. I would ask Takamiya-san to include tremashark into the build and fix the problem.
