### ISSUE TITLE
FlowMultipartRequestがエラーになる

### ISSUE THREAD

**Issue by T-Fukky** [trema/trema-edge#79]
スイッチからフローを取得する以下のコードがエラーとなります。

```
class Sample < Controller
    def switch_ready( datapath_id )
        action = SetField.new( action_set:
                               [EthSrc.new(mac_address: Trema::Mac.new("00:00:00:00:00:01"))])
        ins = ApplyAction.new( actions: [action] )
        send_flow_mod_add( datapath_id, instructions: [ins])

        send_message( datapath_id, FlowMultipartRequest.new(cookie: 0))
    end

    def flow_multipart_reply( datapath_id, message )
        p message
    end
end
```

以下のエラーが出力されます。

```
/home/fukui/trema-edge/ruby/trema/accessor.rb:161:in `block in initialize': Required option mac_address is missing for Trema::Actions::EthSrc (ArgumentError)
```

アクションに EthSrc.new を指定しなければ問題なく動作します。

---

【補足】
エラーの種類としては、EthSrc.new に mac_address: オプションを指定しなかった場合と同じ内容のエラーのようです。

```
class Sample < Controller
    def start
        # 正しくは EthSrc.new( mac_address: Trema::Mac.new("00:00:00:00:00:01") )
        EthSrc.new( Trema::Mac.new("00:00:00:00:00:01") )
    end
end
```

出力されるエラー。

```
/home/fukui/trema-edge/ruby/trema/accessor.rb:171:in `initialize': Required option mac_address missing for Trema::Actions::EthSrc (ArgumentError)
```

ご確認よろしくお願いします。

**Comment by sugyo** [comment]
FlowModのあとに、FlowMultipartRequestを呼ぶと上記の問題が起こるのを確認しました

``` bash
./trema run ./sample.rb  -c src/examples/learning_switch/sample.conf 
```

``` ruby
class Sample < Controller
  def switch_ready datapath_id
    action = SetField.new( action_set: [ EthSrc.new( mac_address: Trema::Mac.new( "00:00:00:00:00:01" ) ) ] )
    ins = ApplyAction.new( actions: [ action ] )
    send_flow_mod_add( datapath_id, instructions: [ ins ] )
    send_flow_multipart_request( datapath_id, cookie: 0 )
  end
  def flow_multipart_reply datapath_id, message
    p message
  end
end
```

**Comment by sugyo** [comment]
unpack_multipart_replyから呼ばれるEthSrc.newに渡す引数が問題でした
